/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.management.app;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.text.DocumentFilter;
import static hr.management.app.Menu.menu_connected_user;

/**
 *
 * @author Haitam
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        identifiant_fld = new javax.swing.JTextField();
        motdepasse_fld = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        afficher_cb = new javax.swing.JCheckBox();
        connecter_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("e-Document");
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/management/app/1498527310_document.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel4.setText("e-Document");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/management/app/OFPPT-Logo-2.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        identifiant_fld.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        identifiant_fld.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        identifiant_fld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                identifiant_fldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                identifiant_fldKeyTyped(evt);
            }
        });

        motdepasse_fld.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        motdepasse_fld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                motdepasse_fldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                motdepasse_fldKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel1.setText("Identifiant :");

        afficher_cb.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        afficher_cb.setText("Afficher");
        afficher_cb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        afficher_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher_cbActionPerformed(evt);
            }
        });

        connecter_btn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        connecter_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/management/app/1492109931_door_in.png"))); // NOI18N
        connecter_btn.setText("Se Connecter");
        connecter_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        connecter_btn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        connecter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecter_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel3.setText("Mot de passe :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connecter_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(motdepasse_fld)
                    .addComponent(identifiant_fld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(afficher_cb)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(identifiant_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(afficher_cb)
                    .addComponent(motdepasse_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(connecter_btn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afficher_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher_cbActionPerformed

        if (afficher_cb.isSelected()) {
            motdepasse_fld.setEchoChar((char) 0);
        } else {
            motdepasse_fld.setEchoChar('•');
        }
    }//GEN-LAST:event_afficher_cbActionPerformed

    private void identifiant_fldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identifiant_fldKeyTyped

        if (identifiant_fld.getText().trim().length() >= 10) {
            evt.consume();
        }

        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_identifiant_fldKeyTyped

    private void motdepasse_fldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motdepasse_fldKeyTyped

        if (motdepasse_fld.getText().trim().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_motdepasse_fldKeyTyped

    private void connecter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecter_btnActionPerformed

        JLabel message1 = new JLabel("Tous les champs sont obligatoires !");
        JLabel message2 = new JLabel("Identifiant ou mot de passe incorrect !");
        JLabel message3 = new JLabel("Connexion avec succès !");
        message1.setFont(new Font("Lucida Sans", Font.PLAIN, 14));
        message2.setFont(new Font("Lucida Sans", Font.PLAIN, 14));
        message3.setFont(new Font("Lucida Sans", Font.PLAIN, 14));

        if (identifiant_fld.getText().trim().isEmpty() || motdepasse_fld.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, message1, "e-Document", JOptionPane.WARNING_MESSAGE);
        } else {
            String loginQuery = "SELECT * FROM utilisateur WHERE identifiant = ? AND mot_de_passe = ?";

            try {
                MyConnection c = new MyConnection(false);
                c.MyExecPrepStat(loginQuery);
                c.pst.setString(1, identifiant_fld.getText());
                c.pst.setString(2, motdepasse_fld.getText());
                c.rs = c.pst.executeQuery();

                if (c.rs.next()) {
                    Menu m = new Menu();

                    String type = c.rs.getString("type");
                    if (!type.equals("Administrateur")) {
                        
                        m.jTabbedPane1.setEnabledAt(3, false);
                        m.supprimer_histo_btn.setEnabled(false);
                        
                    }else{
                        m.jTabbedPane1.setEnabledAt(3, true);
                        m.supprimer_histo_btn.setEnabled(true);
                    }
                    
                        JOptionPane.showMessageDialog(this, message3, "e-Document", JOptionPane.INFORMATION_MESSAGE);
                        m.menu_connected_user.setText(this.identifiant_fld.getText());
                        m.setVisible(true);
                        this.setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(this, message2, "e-Document", JOptionPane.ERROR_MESSAGE);
                    identifiant_fld.setText("");
                    motdepasse_fld.setText("");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_connecter_btnActionPerformed

    private void identifiant_fldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identifiant_fldKeyReleased

        if (!identifiant_fld.getText().trim().isEmpty()) {
            JLabel message = new JLabel("Identifiant doit être alphanumérique !");
            message.setFont(new Font("Lucida Sans", Font.PLAIN, 14));

            if (!identifiant_fld.getText().matches("^[a-zA-Z0-9]+$")) {
                JOptionPane.showMessageDialog(this, message, "e-Document", JOptionPane.WARNING_MESSAGE);
                identifiant_fld.setText("");
            }
        }
    }//GEN-LAST:event_identifiant_fldKeyReleased

    private void motdepasse_fldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motdepasse_fldKeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            
         JLabel message1 = new JLabel("Tous les champs sont obligatoires !");
         JLabel message2 = new JLabel("Identifiant ou mot de passe incorrect !");
         JLabel message3 = new JLabel("Connexion avec succès !");
         message1.setFont(new Font("Lucida Sans", Font.PLAIN, 14));
         message2.setFont(new Font("Lucida Sans", Font.PLAIN, 14));
         message3.setFont(new Font("Lucida Sans", Font.PLAIN, 14));

         if (identifiant_fld.getText().trim().isEmpty() || motdepasse_fld.getText().trim().isEmpty()) {
             JOptionPane.showMessageDialog(this, message1, "e-Document", JOptionPane.WARNING_MESSAGE);
         } else {
             String loginQuery = "SELECT * FROM utilisateur WHERE identifiant = ? AND mot_de_passe = ?";

             try {
                 MyConnection c = new MyConnection(false);
                 c.MyExecPrepStat(loginQuery);
                 c.pst.setString(1, identifiant_fld.getText());
                 c.pst.setString(2, motdepasse_fld.getText());
                 c.rs = c.pst.executeQuery();

                 if (c.rs.next()) {
                     Menu m = new Menu();

                     String type = c.rs.getString("type");
                     if (!type.equals("Administrateur")) {

                         m.jTabbedPane1.setEnabledAt(3, false);
                         m.supprimer_histo_btn.setEnabled(false);

                     }else{
                         m.jTabbedPane1.setEnabledAt(3, true);
                         m.supprimer_histo_btn.setEnabled(true);
                     }

                         JOptionPane.showMessageDialog(this, message3, "e-Document", JOptionPane.INFORMATION_MESSAGE);
                         m.menu_connected_user.setText(this.identifiant_fld.getText());
                         m.setVisible(true);
                         this.setVisible(false);

                 } else {
                     JOptionPane.showMessageDialog(this, message2, "e-Document", JOptionPane.ERROR_MESSAGE);
                     identifiant_fld.setText("");
                     motdepasse_fld.setText("");
                 }
             } catch (Exception ex) {
                 ex.printStackTrace();
             }
         }
        
        }
    }//GEN-LAST:event_motdepasse_fldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox afficher_cb;
    private javax.swing.JButton connecter_btn;
    private javax.swing.JTextField identifiant_fld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField motdepasse_fld;
    // End of variables declaration//GEN-END:variables
}
