/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.management.app;

import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Spyweeb
 */
public class Mon_compte extends javax.swing.JFrame {

    /**
     * Creates new form Mon_compte
     */
    public Mon_compte() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
//        String id = identifiant_fld.getText();
        
//        try
//        {
//            MyConnection c = new MyConnection(false);
//            c.MyExecQuery("SELECT mot_de_passe FROM utilisateur WHERE identifiant = '"+id+"' ");
//            if(c.rs.next())
//            {
//                motdepasse_fld.setText(c.rs.getString(1));
//            }
//        }
//        catch(Exception ex)
//        {
//            
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nouveau_mdp_fld = new javax.swing.JPasswordField();
        identifiant_fld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        afficher_cb = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        motdepasse_fld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("e-Document");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/management/app/1498587862_locked.png"))); // NOI18N
        jLabel1.setText("Mon compte");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel2.setText("Identifiant ");

        nouveau_mdp_fld.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nouveau_mdp_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveau_mdp_fldActionPerformed(evt);
            }
        });
        nouveau_mdp_fld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nouveau_mdp_fldKeyTyped(evt);
            }
        });

        identifiant_fld.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        identifiant_fld.setEnabled(false);
        identifiant_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identifiant_fldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel4.setText("Nouveau mot de passe");

        afficher_cb.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        afficher_cb.setText("Afficher");
        afficher_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher_cbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel3.setText("Mot de passe ");

        motdepasse_fld.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        motdepasse_fld.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(identifiant_fld, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(motdepasse_fld)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(nouveau_mdp_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(afficher_cb)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identifiant_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(motdepasse_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nouveau_mdp_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(afficher_cb)))
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/management/app/1492110472_change_password.png"))); // NOI18N
        jButton1.setText("Changer mot de passe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addComponent(jLabel1))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nouveau_mdp_fldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nouveau_mdp_fldKeyTyped

        if (nouveau_mdp_fld.getText().trim().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_nouveau_mdp_fldKeyTyped

    private void nouveau_mdp_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveau_mdp_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nouveau_mdp_fldActionPerformed

    private void afficher_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher_cbActionPerformed

        if (afficher_cb.isSelected()) {
            nouveau_mdp_fld.setEchoChar((char) 0);
        } else {
            nouveau_mdp_fld.setEchoChar('•');
        }
    }//GEN-LAST:event_afficher_cbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JLabel message = new JLabel("Voulez-vous vraiment changer votre mot de passe ?");
        JLabel message2 = new JLabel("Mot de passe changé avec succès !");
        JLabel message3 = new JLabel("Erreur lors de la modification du mot de passe !");

        message.setFont(new Font("Lucida Sans", Font.PLAIN, 14));
        message2.setFont(new Font("Lucida Sans", Font.PLAIN, 14));
        message3.setFont(new Font("Lucida Sans", Font.PLAIN, 14));
        String options[] = new String[]{"Oui", "Non"};

        String updateQuery = "UPDATE utilisateur SET mot_de_passe = ? WHERE identifiant = ?";
        try {
            MyConnection c = new MyConnection(false);
            c.MyExecPrepStat(updateQuery);
            c.pst.setString(1, nouveau_mdp_fld.getText());
            c.pst.setString(2, identifiant_fld.getText());

            int response = JOptionPane.showOptionDialog(this, message, "e-Document", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, null);
            if (response == JOptionPane.YES_OPTION) {
                c.pst.executeUpdate();
                JOptionPane.showMessageDialog(this, message2, "e-Document", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
            if(c.pst.executeUpdate() == 0)
            {
                JOptionPane.showMessageDialog(this, message3, "e-Document", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void identifiant_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identifiant_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identifiant_fldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mon_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mon_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mon_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mon_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mon_compte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox afficher_cb;
    public static javax.swing.JTextField identifiant_fld;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField motdepasse_fld;
    private javax.swing.JPasswordField nouveau_mdp_fld;
    // End of variables declaration//GEN-END:variables
}
